"""add credit_cases table

Revision ID: 17d65fb8fabc
Revises: 5d943e826f65
Create Date: 2026-03-01 11:18:46.473984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17d65fb8fabc'
down_revision: Union[str, Sequence[str], None] = '5d943e826f65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_cases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('ico_number', sa.String(length=8), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('credit_cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_credit_cases_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_cases_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credit_cases_name'))
        batch_op.drop_index(batch_op.f('ix_credit_cases_is_deleted'))

    op.drop_table('credit_cases')
    # ### end Alembic commands ###
